package swing.calculator;

import java.awt.Color;
import java.awt.Cursor;
import javax.swing.ImageIcon;

/**
 *
 * @author Soumadip Dey 
 * B.Tech in C.S.E(Techno India).
 * Address:-Antira,Uchalan,Burdwan,713427
 * Phone:-8768454982
 * Email:-souma.hitech@gmail.com
 * 
 * 
 */
public class Calculator extends javax.swing.JFrame {

    private ImageIcon titleImg;
    private static int X,Y;
    private static int xx,yy;
    private static String numberOne;
    private static String numberTwo;
    private static char operator;
    private Calculate calculate=new Result();
   
    
    
    
   
    
    /**
     * Creates new form Calculator
     */
    public Calculator() {
        initComponents();
        setImage();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FirstPanel = new javax.swing.JPanel();
        Exit = new javax.swing.JPanel();
        exit = new javax.swing.JLabel();
        Screen = new javax.swing.JPanel();
        screen = new javax.swing.JLabel();
        keypad = new javax.swing.JPanel();
        AC = new javax.swing.JPanel();
        ac = new javax.swing.JLabel();
        C = new javax.swing.JPanel();
        c = new javax.swing.JLabel();
        Divition = new javax.swing.JPanel();
        divition = new javax.swing.JLabel();
        Multiplication = new javax.swing.JPanel();
        multiplication = new javax.swing.JLabel();
        Seven = new javax.swing.JPanel();
        seven = new javax.swing.JLabel();
        Eight = new javax.swing.JPanel();
        eight = new javax.swing.JLabel();
        Nine = new javax.swing.JPanel();
        nine = new javax.swing.JLabel();
        Subtraction = new javax.swing.JPanel();
        subtraction = new javax.swing.JLabel();
        Four = new javax.swing.JPanel();
        four = new javax.swing.JLabel();
        Five = new javax.swing.JPanel();
        five = new javax.swing.JLabel();
        Six = new javax.swing.JPanel();
        six = new javax.swing.JLabel();
        Adition = new javax.swing.JPanel();
        adition = new javax.swing.JLabel();
        One = new javax.swing.JPanel();
        one = new javax.swing.JLabel();
        Two = new javax.swing.JPanel();
        two = new javax.swing.JLabel();
        Three = new javax.swing.JPanel();
        three = new javax.swing.JLabel();
        Percentage = new javax.swing.JPanel();
        percentage = new javax.swing.JLabel();
        Zero = new javax.swing.JPanel();
        zero = new javax.swing.JLabel();
        Point = new javax.swing.JPanel();
        point = new javax.swing.JLabel();
        Equal = new javax.swing.JPanel();
        equal = new javax.swing.JLabel();
        Title = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculator");
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);

        FirstPanel.setBackground(new java.awt.Color(0, 0, 102));
        FirstPanel.setToolTipText(null);
        FirstPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        FirstPanel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                FirstPanelMouseDragged(evt);
            }
        });
        FirstPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                FirstPanelMousePressed(evt);
            }
        });
        FirstPanel.setLayout(null);

        Exit.setBackground(new java.awt.Color(0, 0, 102));
        Exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ExitMouseExited(evt);
            }
        });

        exit.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        exit.setForeground(new java.awt.Color(255, 255, 255));
        exit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exit.setText("X");

        javax.swing.GroupLayout ExitLayout = new javax.swing.GroupLayout(Exit);
        Exit.setLayout(ExitLayout);
        ExitLayout.setHorizontalGroup(
            ExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(exit, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );
        ExitLayout.setVerticalGroup(
            ExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(exit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        FirstPanel.add(Exit);
        Exit.setBounds(260, 0, 30, 20);

        Screen.setBackground(new java.awt.Color(255, 255, 255));
        Screen.setToolTipText(null);

        screen.setFont(new java.awt.Font("RoundorNonCommercial", 0, 48)); // NOI18N
        screen.setForeground(new java.awt.Color(51, 51, 51));
        screen.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        screen.setText("0");

        javax.swing.GroupLayout ScreenLayout = new javax.swing.GroupLayout(Screen);
        Screen.setLayout(ScreenLayout);
        ScreenLayout.setHorizontalGroup(
            ScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ScreenLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(screen, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE)
                .addContainerGap())
        );
        ScreenLayout.setVerticalGroup(
            ScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ScreenLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(screen, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                .addContainerGap())
        );

        FirstPanel.add(Screen);
        Screen.setBounds(10, 32, 271, 86);

        keypad.setBackground(new java.awt.Color(255, 255, 255));
        keypad.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AC.setBackground(new java.awt.Color(255, 255, 255));
        AC.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        AC.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ACMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                ACMouseReleased(evt);
            }
        });

        ac.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        ac.setForeground(new java.awt.Color(255, 102, 0));
        ac.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ac.setText("AC");
        ac.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                acMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout ACLayout = new javax.swing.GroupLayout(AC);
        AC.setLayout(ACLayout);
        ACLayout.setHorizontalGroup(
            ACLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ac, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
        );
        ACLayout.setVerticalGroup(
            ACLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ac, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
        );

        keypad.add(AC, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 0, -1, -1));
        AC.getAccessibleContext().setAccessibleName("");

        C.setBackground(new java.awt.Color(255, 255, 255));
        C.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        C.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        C.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                CMouseReleased(evt);
            }
        });

        c.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        c.setForeground(new java.awt.Color(153, 153, 153));
        c.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        c.setText("C");
        c.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout CLayout = new javax.swing.GroupLayout(C);
        C.setLayout(CLayout);
        CLayout.setHorizontalGroup(
            CLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(c, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
        );
        CLayout.setVerticalGroup(
            CLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(c, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
        );

        keypad.add(C, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 0, -1, -1));

        Divition.setBackground(new java.awt.Color(255, 255, 255));
        Divition.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        Divition.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Divition.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DivitionMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                DivitionMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                DivitionMouseReleased(evt);
            }
        });

        divition.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        divition.setForeground(new java.awt.Color(153, 153, 153));
        divition.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        divition.setText("/");

        javax.swing.GroupLayout DivitionLayout = new javax.swing.GroupLayout(Divition);
        Divition.setLayout(DivitionLayout);
        DivitionLayout.setHorizontalGroup(
            DivitionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(divition, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
        );
        DivitionLayout.setVerticalGroup(
            DivitionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(divition, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
        );

        keypad.add(Divition, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 0, -1, -1));

        Multiplication.setBackground(new java.awt.Color(255, 255, 255));
        Multiplication.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        Multiplication.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Multiplication.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MultiplicationMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                MultiplicationMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                MultiplicationMouseReleased(evt);
            }
        });

        multiplication.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        multiplication.setForeground(new java.awt.Color(153, 153, 153));
        multiplication.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        multiplication.setText("X");

        javax.swing.GroupLayout MultiplicationLayout = new javax.swing.GroupLayout(Multiplication);
        Multiplication.setLayout(MultiplicationLayout);
        MultiplicationLayout.setHorizontalGroup(
            MultiplicationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(multiplication, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
        );
        MultiplicationLayout.setVerticalGroup(
            MultiplicationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(multiplication, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
        );

        keypad.add(Multiplication, new org.netbeans.lib.awtextra.AbsoluteConstraints(202, 0, -1, -1));

        Seven.setBackground(new java.awt.Color(255, 255, 255));
        Seven.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        Seven.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Seven.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                SevenMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                SevenMouseReleased(evt);
            }
        });

        seven.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        seven.setForeground(new java.awt.Color(153, 153, 153));
        seven.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        seven.setText("7");
        seven.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sevenMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout SevenLayout = new javax.swing.GroupLayout(Seven);
        Seven.setLayout(SevenLayout);
        SevenLayout.setHorizontalGroup(
            SevenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(seven, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
        );
        SevenLayout.setVerticalGroup(
            SevenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(seven, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
        );

        keypad.add(Seven, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 57, -1, -1));

        Eight.setBackground(new java.awt.Color(255, 255, 255));
        Eight.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        Eight.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Eight.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                EightMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                EightMouseReleased(evt);
            }
        });

        eight.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        eight.setForeground(new java.awt.Color(153, 153, 153));
        eight.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        eight.setText("8");
        eight.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eightMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout EightLayout = new javax.swing.GroupLayout(Eight);
        Eight.setLayout(EightLayout);
        EightLayout.setHorizontalGroup(
            EightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(eight, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
        );
        EightLayout.setVerticalGroup(
            EightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(eight, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
        );

        keypad.add(Eight, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 57, -1, -1));

        Nine.setBackground(new java.awt.Color(255, 255, 255));
        Nine.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        Nine.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Nine.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                NineMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                NineMouseReleased(evt);
            }
        });

        nine.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        nine.setForeground(new java.awt.Color(153, 153, 153));
        nine.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nine.setText("9");
        nine.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nineMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout NineLayout = new javax.swing.GroupLayout(Nine);
        Nine.setLayout(NineLayout);
        NineLayout.setHorizontalGroup(
            NineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(nine, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
        );
        NineLayout.setVerticalGroup(
            NineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(nine, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
        );

        keypad.add(Nine, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 57, -1, -1));

        Subtraction.setBackground(new java.awt.Color(255, 255, 255));
        Subtraction.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        Subtraction.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Subtraction.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SubtractionMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                SubtractionMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                SubtractionMouseReleased(evt);
            }
        });

        subtraction.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        subtraction.setForeground(new java.awt.Color(153, 153, 153));
        subtraction.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        subtraction.setText("-");

        javax.swing.GroupLayout SubtractionLayout = new javax.swing.GroupLayout(Subtraction);
        Subtraction.setLayout(SubtractionLayout);
        SubtractionLayout.setHorizontalGroup(
            SubtractionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(subtraction, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
        );
        SubtractionLayout.setVerticalGroup(
            SubtractionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(subtraction, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
        );

        keypad.add(Subtraction, new org.netbeans.lib.awtextra.AbsoluteConstraints(202, 57, -1, -1));

        Four.setBackground(new java.awt.Color(255, 255, 255));
        Four.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        Four.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Four.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                FourMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                FourMouseReleased(evt);
            }
        });

        four.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        four.setForeground(new java.awt.Color(153, 153, 153));
        four.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        four.setText("4");
        four.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fourMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout FourLayout = new javax.swing.GroupLayout(Four);
        Four.setLayout(FourLayout);
        FourLayout.setHorizontalGroup(
            FourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(four, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
        );
        FourLayout.setVerticalGroup(
            FourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(four, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
        );

        keypad.add(Four, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 114, -1, -1));

        Five.setBackground(new java.awt.Color(255, 255, 255));
        Five.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        Five.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Five.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                FiveMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                FiveMouseReleased(evt);
            }
        });

        five.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        five.setForeground(new java.awt.Color(153, 153, 153));
        five.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        five.setText("5");
        five.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fiveMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout FiveLayout = new javax.swing.GroupLayout(Five);
        Five.setLayout(FiveLayout);
        FiveLayout.setHorizontalGroup(
            FiveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(five, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
        );
        FiveLayout.setVerticalGroup(
            FiveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(five, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
        );

        keypad.add(Five, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 114, -1, -1));

        Six.setBackground(new java.awt.Color(255, 255, 255));
        Six.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        Six.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Six.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                SixMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                SixMouseReleased(evt);
            }
        });

        six.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        six.setForeground(new java.awt.Color(153, 153, 153));
        six.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        six.setText("6");
        six.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sixMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout SixLayout = new javax.swing.GroupLayout(Six);
        Six.setLayout(SixLayout);
        SixLayout.setHorizontalGroup(
            SixLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(six, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
        );
        SixLayout.setVerticalGroup(
            SixLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(six, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
        );

        keypad.add(Six, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 114, -1, -1));

        Adition.setBackground(new java.awt.Color(255, 255, 255));
        Adition.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        Adition.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Adition.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AditionMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                AditionMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                AditionMouseReleased(evt);
            }
        });

        adition.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        adition.setForeground(new java.awt.Color(153, 153, 153));
        adition.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        adition.setText("+");

        javax.swing.GroupLayout AditionLayout = new javax.swing.GroupLayout(Adition);
        Adition.setLayout(AditionLayout);
        AditionLayout.setHorizontalGroup(
            AditionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(adition, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
        );
        AditionLayout.setVerticalGroup(
            AditionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(adition, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
        );

        keypad.add(Adition, new org.netbeans.lib.awtextra.AbsoluteConstraints(202, 114, -1, -1));

        One.setBackground(new java.awt.Color(255, 255, 255));
        One.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        One.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        One.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                OneMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                OneMouseReleased(evt);
            }
        });

        one.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        one.setForeground(new java.awt.Color(153, 153, 153));
        one.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        one.setText("1");
        one.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                oneMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout OneLayout = new javax.swing.GroupLayout(One);
        One.setLayout(OneLayout);
        OneLayout.setHorizontalGroup(
            OneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(one, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
        );
        OneLayout.setVerticalGroup(
            OneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(one, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
        );

        keypad.add(One, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 171, -1, -1));

        Two.setBackground(new java.awt.Color(255, 255, 255));
        Two.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        Two.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Two.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TwoMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                TwoMouseReleased(evt);
            }
        });

        two.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        two.setForeground(new java.awt.Color(153, 153, 153));
        two.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        two.setText("2");
        two.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                twoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout TwoLayout = new javax.swing.GroupLayout(Two);
        Two.setLayout(TwoLayout);
        TwoLayout.setHorizontalGroup(
            TwoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(two, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
        );
        TwoLayout.setVerticalGroup(
            TwoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(two, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
        );

        keypad.add(Two, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 171, -1, -1));

        Three.setBackground(new java.awt.Color(255, 255, 255));
        Three.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        Three.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Three.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ThreeMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                ThreeMouseReleased(evt);
            }
        });

        three.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        three.setForeground(new java.awt.Color(153, 153, 153));
        three.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        three.setText("3");
        three.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                threeMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout ThreeLayout = new javax.swing.GroupLayout(Three);
        Three.setLayout(ThreeLayout);
        ThreeLayout.setHorizontalGroup(
            ThreeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(three, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
        );
        ThreeLayout.setVerticalGroup(
            ThreeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(three, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
        );

        keypad.add(Three, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 171, -1, -1));

        Percentage.setBackground(new java.awt.Color(255, 255, 255));
        Percentage.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        Percentage.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Percentage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PercentageMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                PercentageMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                PercentageMouseReleased(evt);
            }
        });

        percentage.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        percentage.setForeground(new java.awt.Color(153, 153, 153));
        percentage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        percentage.setText("%");

        javax.swing.GroupLayout PercentageLayout = new javax.swing.GroupLayout(Percentage);
        Percentage.setLayout(PercentageLayout);
        PercentageLayout.setHorizontalGroup(
            PercentageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(percentage, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
        );
        PercentageLayout.setVerticalGroup(
            PercentageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(percentage, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
        );

        keypad.add(Percentage, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 228, -1, -1));

        Zero.setBackground(new java.awt.Color(255, 255, 255));
        Zero.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        Zero.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Zero.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ZeroMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                ZeroMouseReleased(evt);
            }
        });

        zero.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        zero.setForeground(new java.awt.Color(153, 153, 153));
        zero.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        zero.setText("0");
        zero.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                zeroMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout ZeroLayout = new javax.swing.GroupLayout(Zero);
        Zero.setLayout(ZeroLayout);
        ZeroLayout.setHorizontalGroup(
            ZeroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(zero, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
        );
        ZeroLayout.setVerticalGroup(
            ZeroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(zero, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
        );

        keypad.add(Zero, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 228, -1, -1));

        Point.setBackground(new java.awt.Color(255, 255, 255));
        Point.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        Point.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Point.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                PointMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                PointMouseReleased(evt);
            }
        });

        point.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        point.setForeground(new java.awt.Color(153, 153, 153));
        point.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        point.setText(".");
        point.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pointMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout PointLayout = new javax.swing.GroupLayout(Point);
        Point.setLayout(PointLayout);
        PointLayout.setHorizontalGroup(
            PointLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(point, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
        );
        PointLayout.setVerticalGroup(
            PointLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(point, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
        );

        keypad.add(Point, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 228, -1, -1));

        Equal.setBackground(new java.awt.Color(255, 51, 0));
        Equal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        Equal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Equal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EqualMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                EqualMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                EqualMouseReleased(evt);
            }
        });
        Equal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        equal.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        equal.setForeground(new java.awt.Color(255, 255, 255));
        equal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        equal.setText("=");
        Equal.add(equal, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 10, 60, 90));

        keypad.add(Equal, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, 69, 109));

        FirstPanel.add(keypad);
        keypad.setBounds(10, 124, 270, 280);

        Title.setFont(new java.awt.Font("Calibri", 1, 11)); // NOI18N
        Title.setForeground(new java.awt.Color(255, 255, 255));
        Title.setText("Calculator");
        FirstPanel.add(Title);
        Title.setBounds(10, 6, 140, 14);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FirstPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FirstPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 415, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(291, 415));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitMouseEntered
        // TODO add your handling code here:
        Exit.setBackground(Color.red);
    }//GEN-LAST:event_ExitMouseEntered

    private void ExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitMouseExited
        // TODO add your handling code here:
        Exit.setBackground(new Color(0,0,102));
    }//GEN-LAST:event_ExitMouseExited

    private void ExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_ExitMouseClicked

    private void ACMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ACMousePressed
        // TODO add your handling code here:
        AC.setBackground(new Color(204,204,204));
    }//GEN-LAST:event_ACMousePressed

    private void ACMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ACMouseReleased
        // TODO add your handling code here:
        AC.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_ACMouseReleased

    private void CMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CMousePressed
        // TODO add your handling code here:
        C.setBackground(new Color(204,204,204));
    }//GEN-LAST:event_CMousePressed

    private void CMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CMouseReleased
        // TODO add your handling code here:
        C.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_CMouseReleased

    private void DivitionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DivitionMousePressed
        // TODO add your handling code here:
        Divition.setBackground(new Color(204,204,204));
    }//GEN-LAST:event_DivitionMousePressed

    private void DivitionMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DivitionMouseReleased
        // TODO add your handling code here:
        Divition.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_DivitionMouseReleased

    private void MultiplicationMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MultiplicationMousePressed
        // TODO add your handling code here:
        Multiplication.setBackground(new Color(204,204,204));
    }//GEN-LAST:event_MultiplicationMousePressed

    private void MultiplicationMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MultiplicationMouseReleased
        // TODO add your handling code here:
        Multiplication.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_MultiplicationMouseReleased

    private void SevenMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SevenMousePressed
        // TODO add your handling code here:
         Seven.setBackground(new Color(204,204,204));
    }//GEN-LAST:event_SevenMousePressed

    private void SevenMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SevenMouseReleased
        // TODO add your handling code here:
         Seven.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_SevenMouseReleased

    private void EightMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EightMousePressed
        // TODO add your handling code here:
         Eight.setBackground(new Color(204,204,204));
    }//GEN-LAST:event_EightMousePressed

    private void EightMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EightMouseReleased
        // TODO add your handling code here:
        Eight.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_EightMouseReleased

    private void NineMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NineMousePressed
        // TODO add your handling code here:
         Nine.setBackground(new Color(204,204,204));
    }//GEN-LAST:event_NineMousePressed

    private void NineMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NineMouseReleased
        // TODO add your handling code here:
        Nine.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_NineMouseReleased

    private void SubtractionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SubtractionMousePressed
        // TODO add your handling code here:
        Subtraction.setBackground(new Color(204,204,204));
        
    }//GEN-LAST:event_SubtractionMousePressed

    private void SubtractionMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SubtractionMouseReleased
        // TODO add your handling code here:
         Subtraction.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_SubtractionMouseReleased

    private void FourMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FourMousePressed
        // TODO add your handling code here:
        Four.setBackground(new Color(204,204,204));
    }//GEN-LAST:event_FourMousePressed

    private void FourMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FourMouseReleased
        // TODO add your handling code here:
        Four.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_FourMouseReleased

    private void FiveMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FiveMousePressed
        // TODO add your handling code here:
         Five.setBackground(new Color(204,204,204));
    }//GEN-LAST:event_FiveMousePressed

    private void FiveMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FiveMouseReleased
        // TODO add your handling code here:
        Five.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_FiveMouseReleased

    private void SixMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SixMousePressed
        // TODO add your handling code here:
        Six.setBackground(new Color(204,204,204));
    }//GEN-LAST:event_SixMousePressed

    private void SixMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SixMouseReleased
        // TODO add your handling code here:
        Six.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_SixMouseReleased

    private void AditionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AditionMousePressed
        // TODO add your handling code here:
         Adition.setBackground(new Color(204,204,204));
    }//GEN-LAST:event_AditionMousePressed

    private void AditionMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AditionMouseReleased
        // TODO add your handling code here:
        Adition.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_AditionMouseReleased

    private void OneMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OneMousePressed
        // TODO add your handling code here:
         One.setBackground(new Color(204,204,204));
    }//GEN-LAST:event_OneMousePressed

    private void OneMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OneMouseReleased
        // TODO add your handling code here:
        One.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_OneMouseReleased

    private void TwoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TwoMousePressed
        // TODO add your handling code here:
         Two.setBackground(new Color(204,204,204));
    }//GEN-LAST:event_TwoMousePressed

    private void TwoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TwoMouseReleased
        // TODO add your handling code here:
        Two.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_TwoMouseReleased

    private void ThreeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ThreeMousePressed
        // TODO add your handling code here:
         Three.setBackground(new Color(204,204,204));
    }//GEN-LAST:event_ThreeMousePressed

    private void ThreeMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ThreeMouseReleased
        // TODO add your handling code here:
         Three.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_ThreeMouseReleased

    private void PercentageMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PercentageMousePressed
        // TODO add your handling code here:
        Percentage.setBackground(new Color(204,204,204));
    }//GEN-LAST:event_PercentageMousePressed

    private void PercentageMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PercentageMouseReleased
        // TODO add your handling code here:
         Percentage.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_PercentageMouseReleased

    private void ZeroMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ZeroMousePressed
        // TODO add your handling code here:
        Zero.setBackground(new Color(204,204,204));
    }//GEN-LAST:event_ZeroMousePressed

    private void ZeroMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ZeroMouseReleased
        // TODO add your handling code here:
        Zero.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_ZeroMouseReleased

    private void PointMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PointMousePressed
        // TODO add your handling code here:
         Point.setBackground(new Color(204,204,204));
    }//GEN-LAST:event_PointMousePressed

    private void PointMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PointMouseReleased
        // TODO add your handling code here:
        Point.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_PointMouseReleased

    private void EqualMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EqualMousePressed
        // TODO add your handling code here:
         Equal.setBackground(new Color(255,102,0));
         
    }//GEN-LAST:event_EqualMousePressed

    private void EqualMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EqualMouseReleased
        // TODO add your handling code here:
         Equal.setBackground(new Color(255,51,0));
        
    }//GEN-LAST:event_EqualMouseReleased

    private void FirstPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FirstPanelMousePressed
        // TODO add your handling code here:
         xx=evt.getX();
         yy=evt.getY();
         
    }//GEN-LAST:event_FirstPanelMousePressed

    private void FirstPanelMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FirstPanelMouseDragged
        // TODO add your handling code here:
        X=evt.getXOnScreen();
        Y=evt.getYOnScreen();
        
         this.setLocation(X-xx, Y-yy);
         
         
        
    }//GEN-LAST:event_FirstPanelMouseDragged

    private void AditionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AditionMouseClicked
       //adition
      numberOne=screen.getText();
      operator='+';
       screen.setText("0");
        
    }//GEN-LAST:event_AditionMouseClicked

    private void EqualMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EqualMouseClicked
        //equals oprator
        numberTwo=screen.getText();
        switch(operator){
            case '+' :
                screen.setText(calculate.addition(numberOne, numberTwo));
                break;
            case '-':
                screen.setText(calculate.subtraction(numberOne, numberTwo));
                break;
            case 'X':
                screen.setText(calculate.multiplication(numberOne, numberTwo));
                break;
            case '/':
                screen.setText(calculate.divition(numberOne, numberTwo));
                break;
            
        }
        
    
        
        
        
        
    }//GEN-LAST:event_EqualMouseClicked

    private void sevenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sevenMouseClicked
       
        if(screen.getText().equals("0")){
            screen.setText("7");
        }
        else{
            if(screen.getText().length()!=8){
                screen.setText(screen.getText().concat("7"));
            }
            
        }
            
        
    }//GEN-LAST:event_sevenMouseClicked

    private void eightMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eightMouseClicked
       if(screen.getText().equals("0")){
            screen.setText("8");
        }
        else{
            if(screen.getText().length()!=8){
                screen.setText(screen.getText().concat("8"));
            }
            
        }
        
    }//GEN-LAST:event_eightMouseClicked

    private void nineMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nineMouseClicked
        if(screen.getText().equals("0")){
            screen.setText("9");
        }
        else{
            if(screen.getText().length()!=8){
                screen.setText(screen.getText().concat("9"));
            }
            
        }
    }//GEN-LAST:event_nineMouseClicked

    private void fourMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fourMouseClicked
         if(screen.getText().equals("0")){
            screen.setText("4");
        }
        else{
            if(screen.getText().length()!=8){
                screen.setText(screen.getText().concat("4"));
            }
            
        }
       
    }//GEN-LAST:event_fourMouseClicked

    private void fiveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fiveMouseClicked
        if(screen.getText().equals("0")){
            screen.setText("5");
        }
        else{
            if(screen.getText().length()!=8){
                screen.setText(screen.getText().concat("5"));
            }
            
        }
    }//GEN-LAST:event_fiveMouseClicked

    private void sixMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sixMouseClicked
       if(screen.getText().equals("0")){
            screen.setText("6");
        }
        else{
            if(screen.getText().length()!=8){
                screen.setText(screen.getText().concat("6"));
            }
            
        }
        
        
        
    }//GEN-LAST:event_sixMouseClicked

    private void oneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_oneMouseClicked
        if(screen.getText().equals("0")){
            screen.setText("1");
        }
        else{
            if(screen.getText().length()!=8){
                screen.setText(screen.getText().concat("1"));
            }
            
        }
    }//GEN-LAST:event_oneMouseClicked

    private void twoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_twoMouseClicked
        if(screen.getText().equals("0")){
            screen.setText("2");
        }
        else{
            if(screen.getText().length()!=8){
                screen.setText(screen.getText().concat("2"));
            }
            
        }
    }//GEN-LAST:event_twoMouseClicked

    private void threeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_threeMouseClicked
       if(screen.getText().equals("0")){
            screen.setText("3");
        }
        else{
            if(screen.getText().length()!=8){
                screen.setText(screen.getText().concat("3"));
            }
            
        }
    }//GEN-LAST:event_threeMouseClicked

    private void zeroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_zeroMouseClicked
        
        if(screen.getText().equals("0")){
            screen.setText("0");
        }
        else{
            if(screen.getText().length()!=8){
                screen.setText(screen.getText().concat("0"));
            }
            
        }
    }//GEN-LAST:event_zeroMouseClicked

    private void pointMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pointMouseClicked
      
        if(!(screen.getText().contains("."))){
            screen.setText(screen.getText()+".");
        }
       
    }//GEN-LAST:event_pointMouseClicked

    private void cMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cMouseClicked
       
          
               if(screen.getText().length()==1){
                  screen.setText("0"); 
               }
               else{
                   screen.setText(screen.getText().substring(0, (screen.getText().length()-1)));
               }
          
                
    }//GEN-LAST:event_cMouseClicked

    private void acMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_acMouseClicked
       screen.setText("0");
       numberOne="0";
       numberTwo="0";
       
    }//GEN-LAST:event_acMouseClicked

    private void SubtractionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SubtractionMouseClicked
        //subtraction
     
        if((screen.getText().length()==1)&&(screen.getText().equals("0"))){
            screen.setText("-");
            
        }
        else{
                numberOne=screen.getText();
                operator='-';
                 screen.setText("0");
        }
        
        
    }//GEN-LAST:event_SubtractionMouseClicked

    private void MultiplicationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MultiplicationMouseClicked
        // multiplilcation
        numberOne=screen.getText();
        operator='X';
        screen.setText("0");
    }//GEN-LAST:event_MultiplicationMouseClicked

    private void DivitionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DivitionMouseClicked
        numberOne=screen.getText();
        operator='/';
        screen.setText("0");
    }//GEN-LAST:event_DivitionMouseClicked

    private void PercentageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PercentageMouseClicked
        // Percentage
        screen.setText(calculate.percentage(screen.getText()));
    }//GEN-LAST:event_PercentageMouseClicked

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AC;
    private javax.swing.JPanel Adition;
    private javax.swing.JPanel C;
    private javax.swing.JPanel Divition;
    private javax.swing.JPanel Eight;
    private javax.swing.JPanel Equal;
    private javax.swing.JPanel Exit;
    private javax.swing.JPanel FirstPanel;
    private javax.swing.JPanel Five;
    private javax.swing.JPanel Four;
    private javax.swing.JPanel Multiplication;
    private javax.swing.JPanel Nine;
    private javax.swing.JPanel One;
    private javax.swing.JPanel Percentage;
    private javax.swing.JPanel Point;
    private javax.swing.JPanel Screen;
    private javax.swing.JPanel Seven;
    private javax.swing.JPanel Six;
    private javax.swing.JPanel Subtraction;
    private javax.swing.JPanel Three;
    private javax.swing.JLabel Title;
    private javax.swing.JPanel Two;
    private javax.swing.JPanel Zero;
    private javax.swing.JLabel ac;
    private javax.swing.JLabel adition;
    private javax.swing.JLabel c;
    private javax.swing.JLabel divition;
    private javax.swing.JLabel eight;
    private javax.swing.JLabel equal;
    private javax.swing.JLabel exit;
    private javax.swing.JLabel five;
    private javax.swing.JLabel four;
    private javax.swing.JPanel keypad;
    private javax.swing.JLabel multiplication;
    private javax.swing.JLabel nine;
    private javax.swing.JLabel one;
    private javax.swing.JLabel percentage;
    private javax.swing.JLabel point;
    private javax.swing.JLabel screen;
    private javax.swing.JLabel seven;
    private javax.swing.JLabel six;
    private javax.swing.JLabel subtraction;
    private javax.swing.JLabel three;
    private javax.swing.JLabel two;
    private javax.swing.JLabel zero;
    // End of variables declaration//GEN-END:variables

    private void setImage() {
         titleImg=new ImageIcon(this.getClass().getResource("calculator.png"));
        this.setIconImage(titleImg.getImage());


    }
}
